server:
  port : 8083
spring:
  datasource:
    url: jdbc:h2:mem:shoppingDb
    username: konrad
    password: kd
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/db.changelog-master.xml